-- AI-Based Smart Attendance System
-- PostgreSQL schema for Neon, Render, or local PostgreSQL.
-- The application normally creates these tables through SQLAlchemy in app.seed.

CREATE TABLE IF NOT EXISTS admins (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    password_hash VARCHAR NOT NULL,
    role VARCHAR NOT NULL DEFAULT 'admin',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    email_notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roll_number VARCHAR NOT NULL UNIQUE,
    full_name VARCHAR NOT NULL,
    department VARCHAR NOT NULL,
    year VARCHAR NOT NULL,
    section VARCHAR NOT NULL,
    email VARCHAR,
    phone VARCHAR,
    photo_path VARCHAR,
    face_encoding TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_dept_year_section
    ON students (department, year, section);

CREATE TABLE IF NOT EXISTS face_dataset (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    image_path VARCHAR NOT NULL,
    encoding TEXT NOT NULL,
    capture_index INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_face_dataset_student ON face_dataset (student_id);

CREATE TABLE IF NOT EXISTS attendance (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    time TIME NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'Present',
    confidence DOUBLE PRECISION,
    marked_by VARCHAR NOT NULL DEFAULT 'AI',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uniq_student_date UNIQUE (student_id, date)
);

CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance (date);

CREATE TABLE IF NOT EXISTS logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id INTEGER REFERENCES admins(id) ON DELETE SET NULL,
    action VARCHAR NOT NULL,
    details TEXT,
    ip_address VARCHAR,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
